#!/usr/bin/python
import os,sys,shutil,sqlite3

if os.getuid() != 0:
    print("Must run as root!")
    exit()

if sys.platform == "linux":
    INSTALL_PATH = "/opt/gitclass/"
    os.mkdir(INSTALL_PATH[0:-1])
elif sys.platform == "darwin":
    INSTALL_PATH = "/usr/local/bin/gitclass/"
    os.mkdir(INSTALL_PATH[0:-1])
else:
    print("Windows not yet implemented; sorry!")
    exit()

shutil.copy("gitclass",INSTALL_PATH)
