#!/usr/bin/python
import os,sys,shutil

SUPPORTED = ["linux","darwin"]

if os.getuid() != 0:
    print("Must run as root!")
    sys.exit()

install_os = sys.platform

#OS Check
if install_os in SUPPORTED:
    INSTALL_PATH = "/opt/gitclass/"
    if install_os == "darwin":
        INSTALL_PATH = "/usr/local/gitclass/"
    try:
        print("Making install directory")
        os.mkdir(INSTALL_PATH[0:-1])
    except FileExistsError:
        print("Directory exists")
else:
    print("Windows not yet implemented; sorry!")
    sys.exit()

# Copy application, then symlink it for appearance in $PATH
shutil.copy("gitclass",INSTALL_PATH)
try:
    print("Symlinking into $PATH directory")
    os.symlink(INSTALL_PATH + "gitclass", "/usr/local/bin/gitclass")
except FileExistsError:
    print("Symlink exists")

print("Installed to {}".format(INSTALL_PATH))
sys.exit()
