#!/usr/bin/python
import os,sys,shutil

SUPPORTED = ["linux","darwin"]

if os.getuid() != 0:
    print("Must run as root!")
    sys.exit()

install_os = sys.platform
#OS Check
if install_os in SUPPORTED:
    INSTALL_PATH = "/opt/gitclass/"
    if install_os == "darwin":
        INSTALL_PATH = "/usr/local/gitclass/"
    os.mkdir(INSTALL_PATH[0:-1])
else:
    print("Windows not yet implemented; sorry!")
    sys.exit()

shutil.copy("gitclass",INSTALL_PATH)
os.symlink(INSTALL_PATH + "gitclass", "/usr/local/bin/gitclass")

print("Installed to {}".format(INSTALL_PATH))
